### ISSUE TITLE
4.0.0 crashes on MultiMC Fabric 1.15.1

### ISSUE THREAD

**Issue by ggblbl** [GiantNuker/Informed-Load#18]
The game keeps crashing if I turn on Informed Load.
I have tested it with and without the mod to see if it really is Informed Load crashing and it is.
It crashes even before making a config file that I can edit so I can turn off the "Fancy Modloading Status"
Here's the log:
<details>
  <summary>Log</summary>

  ```
  MultiMC version: 0.6.7-1375


Minecraft folder is:
C:/Users/ggblbl/Desktop/MultiMC/instances/1.15.1 Fabric/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_231, using 64-bit architecture.


Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/ggblbl/Desktop/MultiMC/instances/1.15.1 Fabric/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/fabricmc/intermediary/1.15.1/intermediary-1.15.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.17/sponge-mixin-0.8+build.17.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/net/fabricmc/fabric-loader/0.7.3+build.176/fabric-loader-0.7.3+build.176.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/minecraft/1.15.1/minecraft-1.15.1-client.jar

Native libraries:
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/ggblbl/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] advancements-enlarger-1.0.0
  [✔️] Autofish-0.8.5-fabric-mc1.15
  [❌] CraftPresence-Fabric-1.15.1-1.6.0.jar (disabled)
  [✔️] dynamic-fps-1.0.4
  [✔️] fabric-api-0.4.26+build.283-1.15
  [✔️] fabricmod_VoxelMap-1.9.14_for_1.15.1
  [✔️] Hwyla-fabric-1.15-pre4-1.9.19-70
  [✔️] immersive-portals-1.15-4
  [✔️] informedload-4.0.0
  [✔️] lambdacontrols-1.0.1-fabric1.15
  [📁] mamiyaotaru (folder)
  [✔️] modmenu-1.8.2+build.18
  [✔️] mousewheelie-1.3.10+1.15.1-pre1
  [✔️] notenoughcrashes-1.1.5+1.15.1
  [✔️] okzoomer-1.0.3
  [✔️] RoughlyEnoughItems-3.2.33
  [✔️] simplexterrain-0.4.3

Params:
  --username  --version MultiMC5 --gameDir C:/Users/ggblbl/Desktop/MultiMC/instances/1.15.1 Fabric/.minecraft --assetsDir C:/Users/ggblbl/Desktop/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx8192m, -Duser.language=en]


Minecraft process ID: 11368


Using onesix launcher.

[13:23:29] [main/INFO]: Loading for game Minecraft 1.15.1
[13:23:31] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-keybindings-v0: used 0.1.1+933c24c242, also found 0.1.1+dfdb52d695
 - Conflicting versions found for fabric-api-base: used 0.1.2+b7f9825d95, also found 0.1.2+28f8190f42
 - Conflicting versions found for fabric-networking-v0: used 0.1.7+12515ed995, also found 0.1.7+12515ed975
 - Conflicting versions found for fabric-events-interaction-v0: used 0.2.6+12515ed995, also found 0.2.6+12515ed975
 - Conflicting versions found for fabric-resource-loader-v0: used 0.1.10+06c939b375, also found 0.1.10+06c939b395
 - Conflicting versions found for fabric-tag-extensions-v0: used 0.1.3+abd9158095, also found 0.1.3+d423005742
 - Conflicting versions found for fabric-mining-levels-v0: used 0.1.1+28f8190f42, also found 0.1.1+b7f9825d95
 - Conflicting versions found for fabric-events-lifecycle-v0: used 0.1.2+b7f9825d95, also found 0.1.2+b7f9825de8
[13:23:31] [main/WARN]: Mod `autoconfig1` (1.2.0+mc1.14.4) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[13:23:31] [main/WARN]: Mod `cloth-config` (0.2.1+build.14) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[13:23:31] [main/WARN]: Mod `tweed` (2.2.8) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[13:23:31] [main/INFO]: [FabricLoader] Loading 58 mods: fabric-renderer-api-v1@0.2.7+f3d8141b95, fabric-keybindings-v0@0.1.1+933c24c242, notenoughcrashes@1.1.4+1.15.1, fabricloader@0.7.3+build.176, org_aperlambda_lambdajcommon@1.7.2, fabric-containers-v0@0.1.3+b7f9825d95, fabric-dimensions-v1@0.2.3+06c939b395, fabric-api-base@0.1.2+b7f9825d95, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d95, fabric-textures-v0@1.0.4+821cdba795, com_electronwill_night-config_core@3.5.3, fabric-rendering-fluids-v1@0.1.6+12515ed995, waila@1.9.19, simplexterrain@0.4.3, autoconfig1@1.2.0+mc1.14.4, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, immersive_portals@0.4, fabric-renderer-registries-v1@2.0.1+5a0f9a6095, fabric-loot-tables-v1@0.1.5+e08a730595, dynamicfps@1.0.4, fabric@0.4.26+build.283-1.15, fabric-particles-v1@0.1.1+dfdb52d695, fabric-networking-v0@0.1.7+12515ed995, cloth@1.1.0, okzoomer@1.0.3, minecraft@1.15.1, fabric-networking-blockentity-v0@0.2.3+e08a730595, modmenu@1.8.2+build.18, lambdacontrols@1.0.1, informedload@4.0.0, fabric-renderer-indigo@0.2.21+175d0eb895, autofish@0.8.5, advancements-enlarger@1.0.0, com_electronwill_night-config_toml@3.5.3, fabric-biomes-v1@0.1.5+3b05f68e95, roughlyenoughitems@3.2.33, fabric-events-interaction-v0@0.2.6+12515ed995, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-rendering-v0@1.1.0+5341049095, mousewheelie@1.3.10+1.15.1-pre1, fabric-rendering-v1@0.1.0+5341049095, cloth-config2@2.5.3, amecs@1.2.9+1.15-pre5, autoconfig1u@1.2.4, fabric-resource-loader-v0@0.1.10+06c939b375, fabric-content-registries-v0@0.1.3+b7f9825d95, fabric-tag-extensions-v0@0.1.3+abd9158095, fabric-commands-v0@0.1.2+b7f9825d95, fabric-registry-sync-v0@0.2.6+f3d8141b95, cloth-config@0.2.1+build.14, fabric-mining-levels-v0@0.1.1+28f8190f42, voxelmap@1.9.14, fabric-events-lifecycle-v0@0.1.2+b7f9825d95, fabric-models-v0@0.1.0+dfdb52d695, fabric-item-groups-v0@0.1.6+ec40b2e195, fabric-object-builders-v0@0.1.3+e4c9a9c395, tweed@2.2.8, org_jetbrains_annotations@17.0.0
[13:23:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/ggblbl/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.17/sponge-mixin-0.8+build.17.jar Service=Knot/Fabric Env=CLIENT
[13:23:33] [main/WARN]: @Redirect conflict. Skipping informedload.mixins.json:MixinMinecraftClient->@Redirect::stopFabricInit(Ljava/io/File;Ljava/lang/Object;)V with priority 1000, already redirected by notenoughcrashes.mixins.json:client.MixinMinecraftClient->@Redirect::redirectModEntryPoints(Ljava/io/File;Ljava/lang/Object;)V with priority 1000
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector stopFabricInit(Ljava/io/File;Ljava/lang/Object;)V in informedload.mixins.json:MixinMinecraftClient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap informedLoad-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[13:23:33] [main/WARN]: @Redirect conflict. Skipping informedload.mixins.json:MixinMinecraftClient->@Redirect::stopFabricInit(Ljava/io/File;Ljava/lang/Object;)V with priority 1000, already redirected by notenoughcrashes.mixins.json:client.MixinMinecraftClient->@Redirect::redirectModEntryPoints(Ljava/io/File;Ljava/lang/Object;)V with priority 1000
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector stopFabricInit(Ljava/io/File;Ljava/lang/Object;)V in informedload.mixins.json:MixinMinecraftClient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap informedLoad-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:357)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:172)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector stopFabricInit(Ljava/io/File;Ljava/lang/Object;)V in informedload.mixins.json:MixinMinecraftClient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap informedLoad-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	... 22 more
Exiting with -1
2019-12-31 13:23:33,509 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector stopFabricInit(Ljava/io/File;Ljava/lang/Object;)V in informedload.mixins.json:MixinMinecraftClient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap informedLoad-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:539)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:344)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main$2.run(Main.java:141)
Process exited with code -1.
MultiMC: Log upload triggered at: 31 Dec 2019 13:24:10 +0100

  ```
</details>

**Comment by TheByKotik** [comment]
Not Enough Crashes conflict with this mod as i know.
Try to disable Not Enough Crashes.

**Comment by ggblbl** [comment]
Ah that does it!
I didn't really need that mod anyway.
Thanks!
