### ISSUE TITLE
Incompatible with OK Zoomer

### ISSUE THREAD

**Issue by lorilith** [GiantNuker/Informed-Load#23]
MC 1.15.2
enabling both Informed Load (4.0.0) and OK Zoomer (2.1.X) will cause crashes unless "io.github.joaoh1.okzoomer.OkZoomer" is excluded.

crash:
`
java.lang.RuntimeException: Config 'class io.github.joaoh1.okzoomer.OkZoomerConfig' has not been registered
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigHolder(AutoConfig.java:57)
	at net.minecraft.class_312.<init>(class_312.java:37)
	at net.minecraft.class_310.<init>(class_310.java:428)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
`

**Comment by GiantNuker** [comment]
Issue with how I moved injection points. fixable

**Comment by joaoh1** [comment]
I patched this issue in my side on Ok Zoomer 2.1.4 by registering the config sooner. Informed Load works with Ok Zoomer now without having to exclude its entrypoint
